### ISSUE TITLE
Access hidden layers of character-bert

### ISSUE THREAD

**Issue by vguptai** [helboukkouri/character-bert#10]
Hi @helboukkouri,

Thanks for sharing this amazing work ! 

I wanted to tap out the 13 hidden layers activations also. For doing that I pass `output_hidden_states=True` to the encoder in the `forward` function. Now, the model returns a tuple with 3 entries where 3rd entry contains a list of activations for the 13 layers. Please let me know if this is the correct way.

The outputs of each layers are of the shape [Num_words, 11, 768]. Would it be alright to take the average across the 11 characters to get the intermediate word representation or you would recommend something else. Actually, I was expecting the outputs of each layer to have the form [Num_words*11, 768] (similar to word piece) or simple [Num_words, 768].

Kindly help me in understanding this aspect.

**Comment by helboukkouri** [comment]
Hi @vguptai, thank you for the interest in CharacterBERT 😊

About getting the hidden activations of the model, I think you should have a look at [these lines](https://github.com/helboukkouri/character-bert/blob/main/modeling/character_bert.py#L178-L195) from `CharacterBertModel`'s forward. Here you can see that using the `output_hidden_states` parameters does not actually have any effect. You can also see that the model always returns the variable `outputs` which is defined as:
```
outputs = (sequence_output, pooled_output,) + encoder_outputs[1:]
```
So basically the output is always a tuple with the final layer representations `(batch size, num words, 768)`, the pooled (CLS) representation `(batch size, 768)`, the other 11 layers representations `(batch size, 11, num words, 768)`. So if you'd like to use the 12 transformer layer hidden representations you should be able to do something like:
```

last_layer_reprentations, _, other_layers_representations = outputs
```

But this would only get you the transformer layer outputs and you would be missing the "CharacterCNN representations". If you wan to get that as well, I think you will have to edit the `CharacterBertModel` forward to also output the variable `embedding_output `. Maybe something like:
```
outputs = (sequence_output, pooled_output, encoder_outputs[1:], embedding_output)
```

In any case, the 11 you see in the shape is not the number of characters. In fact, despite the model attending to token characters, this only happens within the CharacterCNN module and the model is actual word-level. So no need of averaging anything, the representations you get are actually token/word representations 😊

Let me know if there is something else that needs clarification.
