### ISSUE TITLE
unroling of the word representations for the loss function

### ISSUE THREAD

**Issue by XMaster96** [helboukkouri/character-bert#11]
I was reading the paper, and wondering how you exactly handle the unroling of the word representations for the loss function. I found the paper leaking a bit in detail and I also wasn't able to easily find it in your implementation.
Could you tell me how char-bert is handling that?

Thanks
XMaster

**Comment by helboukkouri** [comment]
Hi @XMaster96, I am not sure I understand your question correctly. In any case, the loss/optimization part is exactly the same as with plain BERT.

As for the implementation, you can check this:
https://github.com/helboukkouri/transformers/blob/add-character-bert/src/transformers/models/character_bert/modeling_character_bert.py#L1271-L1275

I hope this helps 😊
