### ISSUE TITLE
CharacterBERT in information retrieval task

### ISSUE THREAD

**Issue by ArvinZhuang** [helboukkouri/character-bert#20]
Hi @helboukkouri, I think you may be interested in our SIGIR2022 work [CharacterBERT and Self-Teaching for Improving the Robustness of Dense Retrievers on Queries with Typos](https://arxiv.org/pdf/2204.00716.pdf). We found that CharacterBERT plus some adversarial training technics can make dense retrievers much more robust on misspelled queries in the IR task.

**Comment by helboukkouri** [comment]
Hey, interesting work! Thanks for sharing 🙏🏼
Glad you could leverage CharacterBERT in your research 🚀
