### ISSUE TITLE
MLM head pre-trained weights of character-bert

### ISSUE THREAD

**Issue by alexlimh** [helboukkouri/character-bert#21]
Hi,

I just found that the input embeddings of character-bert encoder are not tied with the output MLM weights. I would appreciate it if you could also release the pre-trained general-character-bert models with the MLM head pre-trained weights, as our group would like to explore further pre-training using character-bert.

Many Thanks

**Comment by helboukkouri** [comment]
You can try and use the code from: https://huggingface.co/helboukkouri/character-bert/discussions/1

I'll work on an official integration into the tranformers library when I can :)
