### ISSUE TITLE
Does this support mask filling task?

### ISSUE THREAD

**Issue by ZonglinL** [helboukkouri/character-bert#23]
Hello @helboukkouri ,

I am wondering if this model supports mask filling task. If so, how will the <mask> token be added? Thank you!

**Comment by helboukkouri** [comment]
If you are talking about maked language modeling, it is actually trained using that.
There is a repository for the pretraining code of CharacterBERT, however it's quite old now so I'll need to give it a quick test/update. In the meantime you can still check it at: https://github.com/helboukkouri/character-bert-pretraining
