### ISSUE TITLE
How do I pre-train CharacterBERT?

### ISSUE THREAD

**Issue by gianfilippo** [helboukkouri/character-bert#4]
Hi,

can you please share the code/tutorial to train from scratch ?

Thanks

**Comment by kleag** [comment]
Does this answer your question?
https://github.com/helboukkouri/character-bert#how-do-i-pre-train-characterbert

**Comment by gianfilippo** [comment]
Hi,

thanks I notice that already, but it takes to an almost empty folder.

Best
Gianfilippo

**Comment by helboukkouri** [comment]
Hi @gianfilippo, I am currently working on cleaning up and making the pre-training code a bit easier tu use. That is the reason why it is not yet public. I will post a message on this issue as soon as it is.

Thank you for your interest 😊

**Comment by helboukkouri** [comment]
The code for pre-training CharacterBERT is now available at: https://github.com/helboukkouri/character-bert-pretraining

Hope you will find it useful 😊

**Comment by gianfilippo** [comment]
Thanks! I will look into it right away.
