### ISSUE TITLE
Huggingface implementation

### ISSUE THREAD

**Issue by Tahlor** [helboukkouri/character-bert#6]
Great stuff! I saw you have an active huggingface implementation:
https://huggingface.co/helboukkouri/character-bert/tree/main

Is this live? Or when do you expect it to be?

Thanks!

**Comment by helboukkouri** [comment]
Hi @Tahlor, thanks for the support :) So, the implementation you're looking at should be useable but it's still not part of the transformers library. There is an active pull request for that here: https://github.com/huggingface/transformers/pull/10053

I'll update the repo's README as soon as it's merged. For now you may use the code from the fork you linked but it may have some (probably minor) bugs. If you do find any, please let me know 😊

**Comment by helboukkouri** [comment]
By the way @Tahlor, although the PR hasn't been merged yet I think that you can start using the code from the fork. I'm just waiting for a couple more reviews before the merge :)

**Comment by helboukkouri** [comment]
If anybody is still interested, there is a way to load CharacterBERT through the transformers library:
https://huggingface.co/helboukkouri/character-bert/discussions/1
